CREATE TABLE questions (
	Id BIGINT AUTO_INCREMENT PRIMARY KEY,
	Email VARCHAR(255) NOT NULL,
	Keyword VARCHAR(255) NOT NULL,
	Question1 TEXT,
	Answers1 TEXT,
	Feedback1 TEXT,
	Question2 TEXT,
	Answers2 TEXT,
	Feedback2 TEXT,
	Question3 TEXT,
	Answers3 TEXT,
	Feedback3 TEXT,
	Question4 TEXT,
	Answers4 TEXT,
	Feedback4 TEXT,
	Question5 TEXT,
	Answers5 TEXT,
	Feedback5 TEXT,
	Question6 TEXT,
	Answers6 TEXT,
	Feedback6 TEXT,
	Question7 TEXT,
	Answers7 TEXT,
	Feedback7 TEXT,
	Question8 TEXT,
	Answers8 TEXT,
	Feedback8 TEXT,
	Question9 TEXT,
	Answers9 TEXT,
	Feedback9 TEXT,
	Question10 TEXT,
	Answers10 TEXT,
	Feedback10 TEXT
)